### ISSUE TITLE
Local installation is broken

### ISSUE THREAD

**Issue by dzek69** [digital-loukoum/tsc-esm#2]
Hi

I installed this lib locally (`yarn add @digitak/tsc-esm --dev` but I could do `npm i @digitak/tsc-esm` for the same result), as a result I got:

`node_modules/bin/tsc-esm` file with contents:
```
#!/usr/bin/env node
import { build } from "../library/index.js"
build().catch(error => {
	console.error(error)
	process.exit(1)
})
```

which of course breaks, because I don't have `node_modules/library/index.js` file installed.

Also README seems to be wrong and with both `Global installation` and `Local installation` it suggests installing the lib with `-g` flag, which of course means `global`.

**Comment by jrkienle** [comment]
I think this might be the wrong cause here. I went ahead and logged `build` when I ran this and that was returning a function, however it didn't have a return value after it was called. Since the return value was undefined, node threw an error trying to call catch from undefined. I put out #4 to fix this, hopefully @Gin-Quin will get it reviewed soon

**Comment by dzek69** [comment]
Oh, right,
if the `bin` file is hardlinked and node resolves the link before running the code and treat the local import as from where this library actually exists then yeah, you're right.
I was too tired to really think on what's happening, because of that `-g` everywhere i thought this package may be ultimately broken for local installs, my bad

anyway, looking at your fix - i don't know if that's necessary at all. `build` in current form should never throw, so i guess just the `build()` call in this file should be enough

**Comment by jrkienle** [comment]
> anyway, looking at your fix - i don't know if that's necessary at all. build in current form should never throw, so i guess just the build() call in this file should be enough

You're probably right, the only reason I left that in was to keep the same expected behavior that was originally implemented. We'll see what the maintainers say but I think we could probably remove that

**Comment by Gin-Quin** [comment]
I merged @jrkienle PR so that should work from version 3.1.2 👍
